### ISSUE TITLE
感谢，非常喜欢这个简单的又好看的主题

### ISSUE THREAD

**Issue by jackloves111** [yangJiang-create/halo-theme-xue2020#1]

**Comment by jackloves111** [comment]
@jiangmiemie 请问怎么在原版的基础上修改目录样式，我比较喜欢你做的目录样式但是目录并不是自动跳出的，而是要手动开关

**Comment by jiangyangcreate** [comment]
你好，感谢你的支持。不是自动跳出是因为手机端用了目录会不好浏览，对应的代码逻辑在‘source\js\main.js’中，搜索yuedu即可看到我的备注
